- hosts: testhost,testhost2
  gather_facts: no
  tasks:
  - block:
    - name: EXPECTED FAILURE fail on testhost
      fail:
      when: inventory_hostname == 'testhost'
    - debug: msg="still executing in block"
    rescue:
    - meta: clear_host_errors
    always:
    - debug: msg="executing in always"
    any_errors_fatal: yes

  - debug: msg="continue executing after recovering from failure"

- hosts: testhost,testhost2
  gather_facts: no
  tasks:
  - block:
    - name: EXPECTED FAILURE fail on testhost
      fail:
      when: inventory_hostname == 'testhost'
    - debug: msg="still executing in block"
    always:
    - debug: msg="executing in always"
    any_errors_fatal: yes

  - debug: msg="task_after_block_should_not_run"
